---
- name: Ensure basic packages are there
  apt:
   name: ['gcc', 'git', 'ansible']
   update_cache: true
   state: present

- name: Ensure needed python libraries are installed
  pip: name=['pushbullet.py', 'RPi.GPIO', 'httplib2']
       state=latest
       executable=pip2
       extra_args='--exists-action=w'

- name: Pull down the repo
  git: repo=https://github.com/aikidoka/robocoop.git
       dest={{ install_dir }}

- name: Instantiate the config
  template: src=robocoop.cfg.j2
            dest={{ install_dir }}/robocoop.cfg

- name: Instantiate the program file
  template: src=robocoop.py.j2
            dest={{ install_dir }}/robocoop.py

- name: Instantiate the poller file
  template: src=poller.py.j2
            dest={{ install_dir }}/poller.py

- name: Modify the motd
  template: src=motd.j2
            dest=/etc/motd

- name: Install bash aliases
  template: src=chicken-door-aliases.sh.j2
            dest=/etc/profile.d/chicken-door-aliases.sh

- name: Create robocoop service
  template: src=robocoop.service.j2
            dest=/etc/systemd/system/robocoop.service

- name: Create auto-update service
  template: src=robocoop-update.service.j2
            dest=/etc/systemd/system/robocoop-update.service

- name: Gather sun phases
  uri: url=http://api.wunderground.com/api/{{ wunderground_api_key }}/astronomy/q/{{ zipcode }}.json
       return_content=yes
  register: sun_phases
  tags: timers

- name: Generate morning timer
  template: src=robocoop-morning.timer.j2
            dest=/etc/systemd/system/robocoop-morning.timer
  notify: reload systemd
  tags: timers

- name: Generate evening timer
  template: src=robocoop-evening.timer.j2
            dest=/etc/systemd/system/robocoop-evening.timer
  notify: reload systemd
  tags: timers

- name: Generate update timer
  template: src=robocoop-update.timer.j2
            dest=/etc/systemd/system/robocoop-update.timer
  notify: reload systemd

- meta: flush_handlers
  tags: timers

- name: Enable the timers
  systemd: name={{ item }}
           enabled=yes
           state=started
  with_items:
      - robocoop-morning.timer
      - robocoop-evening.timer
      - robocoop-update.timer
  tags: timers
